### ISSUE TITLE
sampleAccess

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [IGSN/metadata#18]
Is this element for indicating the status of a sample (destroyed), registration (duplicate/deprecated) or metadata (private/public)?

**Comment by jklump** [comment]
This element indicates whether the sample is available for reuse beyond the original contributor, not whether it exists.

It is unclear in the description whether this refers to the metadata or to the sample itself.

**Comment by jklump** [comment]
The permitted values for sampleAccess are still unclear and need to be defined. See #35 .
