### ISSUE TITLE
collectionTime does not allow time ranges

### ISSUE THREAD

**Issue by ulbricht** [IGSN/metadata#25]
Currently collectionTime is defined as xs:datetime. This does not allow to define time ranges.

**Comment by jklump** [comment]
Suggested action: specify time period and time instance. Rename element to "Date".

**Comment by kitchenprinzessin3880** [comment]
timeinstant and time interval have been added to the schema; see dev branch.

**Comment by jklump** [comment]
Pulled into main branch.
